/* eslint-disable @stylistic/quotes */
import m from "mithril";

export const siteboxGalleryStyles: string[] = [
  `.site-box{position:relative;overflow:hidden;background:url(//timmy.nekoweb.org/assets/images/sitebox/bg.gif)center center/cover no-repeat;border:2px solid #000}.site-box>a>.sitefeature{display:none!important}.site-box:after{content:"";position:absolute;top:-30px;right:-125px;width:250px;height:250px;filter:drop-shadow(-10px 0 4px rgba(0,0,0,.5));background:url(//timmy.nekoweb.org/assets/images/sitebox/bg2.gif)no-repeat;background-size:contain;z-index:20;pointer-events:none}.site-box>a{position:absolute!important;top:0;left:0;width:100%;height:100%;display:block;text-decoration:none;z-index:5}.site-box>a>p{position:absolute!important;left:0;bottom:0;width:100%;margin:0;padding:5px 7px;box-sizing:border-box;background:rgba(0,0,0,.65);color:#fff;font:16px monospace;text-align:left;text-transform:lowercase}.site-box:hover>a>p{color:#eddc59}.site-box>a>span{display:none!important}.site-title{display:none!important}.follow{display:none!important}.top-dot{display:none!important}.bottom-dot{display:none!important}.post-box{background:#282a36;border:4px solid #433f55;border-top:0;border-radius:0;padding:5px 0 0 7px;color:#fff;font-family:monospace}.post-box:before{content:"";position:absolute;top:0;left:0;width:100%;height:27px;background:#433f55}.post-box .post-title{font:20px monospace}.post-box .post-description{font:16px monospace;margin-top:5px}`,
  `.site-box{position:relative;background-image:url(//timmy.nekoweb.org/assets/images/sitebox/votv_old/bg.png);background-position:center;background-size:cover;border:2px solid #000}.site-box:hover{background-image:url(//timmy.nekoweb.org/assets/images/sitebox/votv_old/hv.png);border:2px solid #000}.site-box:hover p{color:#eddc59}.site-box>a>p{display:inline-block;font-family:monospace;text-transform:uppercase;background:#000;padding:4px 6px;font-size:15px;margin-top:165px;margin-bottom:0;border-radius:0 5px 0 0;color:#b7e3bd}.site-box .follow{display:none}.site-box>a>span{display:none}.site-box>a>.sitefeature{display:none}.post-box{background:#282a36;border:5px solid #433f55;border-top:0;border-radius:0;padding-top:10px;padding-left:10px;padding-bottom:0;color:#3ed962;font-family:monospace;font-size:16px;font-weight:700}.post-box::before{content:"";position:absolute;top:0;left:0;width:100%;height:40px;background:#433f55}.post-box p{font-family:monospace}.post-box .post-title{color:#fff;font:25px monospace;font-weight:700;margin-top:20px}.post-box .post-description{font:16px monospace;font-weight:500;color:#fff;margin-top:12px}`,
  `.site-box{position:relative;background-image:url(//timmy.nekoweb.org/assets/images/sitebox/17776_old/bg.png);background-position:center;background-size:cover;border:2px solid #000}.site-box:hover{background-image:url(//timmy.nekoweb.org/assets/images/sitebox/17776_old/hv.png);border:2px solid #000}.site-box:hover p{color:#eddc59}.site-box>a>p{display:inline-block;font-family:monospace;text-transform:uppercase;background:#000;padding:4px 6px;font-size:15px;margin-top:165px;margin-bottom:0;border-radius:0 5px 0 0;color:#b7e3bd}.site-box .follow{display:none}.site-box>a>span{display:none}.site-box>a>.sitefeature{display:none}.post-box{background:#282a36;border:5px solid #433f55;border-top:0;border-radius:0;padding-top:10px;padding-left:10px;padding-bottom:0;color:#3ed962;font-family:monospace;font-size:16px;font-weight:700}.post-box::before{content:"";position:absolute;top:0;left:0;width:100%;height:40px;background:#433f55}.post-box p{font-family:monospace}.post-box .post-title{color:#fff;font:25px monospace;font-weight:700;margin-top:20px}.post-box .post-description{font:16px monospace;font-weight:500;color:#fff;margin-top:12px}`
];

const htmlMarkup = `<div id="sitebox-gallery-template" class="site-box t-classic" style="width:275px!important;height:190px!important;position:relative!important"><span class="top-dot"></span><a href="https://timmy.nekoweb.org/" target="_blank" rel="noopener noreferrer"><div class="sitefeature"><img class="screenshot" alt=""></div><p>timmy.nekoweb.org</p><span class="site-title"></span><br></a><span class="bottom-dot"></span></div>`;

export const renderSiteboxIframe = (css: string) =>
  m("iframe.sitebox-gallery-frame", {
    srcdoc: `<!doctype html><html><head><base href="/"><style>html,body{margin:0;padding:0}${css}</style></head><body>${htmlMarkup}</body></html>`
  });
