on:
  workflow_dispatch:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.head_commit.message, '[deploy]')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: deploy2nekoweb
        uses: indiefellas/deploy2nekoweb@main
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-domain: 'timmy.nekoweb.org'
          nekoweb-username: 'timmy'
          directory: 'public'
