on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (Clone)
        uses: actions/checkout@v4

      - name: Instalando PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 11

      - name: Instalando NODE
        uses: actions/setup-node@v4
        with:
          node-version: 'lts'
          cache: 'pnpm'

      - name: Instalando Dependencias
        run: pnpm install --frozen-lockfile

      - name: Compilando Sitio
        run: pnpm build

      - name: Deploy en Nekoweb
        uses: indiefellas/deploy2nekoweb@main
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-domain: 'timmy.nekoweb.org'
          nekoweb-username: 'timmy'
          directory: 'public'